name: CI

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_lint_test:
    name: "build, lint, test (${{ matrix.toolchain }})"
    runs-on: "rust"
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: rustup component add clippy
      - run: cargo build --verbose
      - run: cargo clippy
      - run: cargo test --verbose

  # generate documentation
  doc:
    name: "doc"
    runs-on: "rust"
    steps:
      - uses: actions/checkout@v5
      - run: cargo doc

  # check code coverage (disabled in forgejo for now)
  # - fails if coverage drops below 95%
  # - generates artifact "tarpaulin-report.zip"
  coverage:
    name: "coverage"
    runs-on: "rust"
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # install tarpaulin
      # note: comically slow w/o cache; try binstall instead
      - run: cargo install cargo-tarpaulin

      # run tarpaulin with llvm engine (required for forgejo)
      - run: cargo +nightly tarpaulin --engine llvm -o html --timeout 120 --fail-under 95

      # upload report
      # note: forgejo does not support actions/upload-artifact@v6
      - uses: actions/upload-artifact@v3
        with:
          name: tarpaulin-report
          path: tarpaulin-report.html
