name: CI

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_lint_test:
    name: "build, lint, test (${{ matrix.toolchain }})"
    runs-on: "rust"
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: rustup component add clippy
      - run: cargo build --verbose
      - run: cargo clippy
      - run: cargo test --verbose

  # generate documentation
  doc:
    name: "doc"
    runs-on: "rust"
    steps:
      - uses: actions/checkout@v5
      - run: cargo doc

  # lint all markdown
  lint_markdown:
    name: "lint markdown"
    runs-on: "rust"
    steps:
      - uses: actions/checkout@v5
      - run: npm config set update-notifier false
      - run: npx -y markdownlint-cli README.md

  # check code coverage (disabled in forgejo for now)
  # - fails if coverage drops below 95%
  # - generates artifact "tarpaulin-report.zip"
  coverage:
    name: "coverage"
    runs-on: "rust"
    steps:
      - run: echo "DATESTAMP=$(date +%Y%m%d)" >> $FORGEJO_ENV
      - uses: actions/checkout@v5
      - uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # install cargo-binstall, then use it to install cargo-tarpaulin
      - run: cargo install cargo-binstall
      - run: cargo binstall --no-confirm cargo-tarpaulin

      # run tarpaulin with llvm engine (required for forgejo)
      - run: cargo +nightly tarpaulin --engine llvm -o html --timeout 120 --fail-under 95
      - run: mv tarpaulin-report.html polycvss-coverage-${{ env.DATESTAMP }}.html

      # upload report
      # note: forgejo does not support actions/upload-artifact@v6
      - uses: actions/upload-artifact@v3
        with:
          name: polycvss-coverage-${{ env.DATESTAMP }}
          path: polycvss-coverage-${{ env.DATESTAMP }}.html

# busted_coverage:
# - uses: ./.forgejo/actions/tarpaulin
#   with:
#     # llvm engine (required for non-x86 and forgejo)
#     engine: "llvm"
# 
#     # generate html report
#     output: "html"
# 
#     # time out after 120s
#     timeout: "120"
# 
#     # fail under 95% coverage
#     fail_under: "95"
# 
# # rename coverage report
# - run: mv tarpaulin-report.html polycvss-coverage-${{ env.DATESTAMP }}.html
