# copied from .github/workflows/ci.yml w/ forgejo-specific mods
name: CI

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_lint_test:
    name: "build, lint, test (${{ matrix.toolchain }})"
    runs-on: "rust"
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: rustup component add clippy
      - run: cargo build --verbose
      - run: cargo clippy
      - run: cargo test --verbose

  doc:
    name: "doc"
    runs-on: "rust"
    steps:
      - uses: actions/checkout@v4
      - run: cargo doc

  # check code coverage (disabled in forgejo)
  # - fails if coverage drops below 95%
  # - generates "tarpaulin-report.zip" artifact
  # coverage:
  #   name: "coverage"
  #   runs-on: "rust-x86-64"

  #   container:
  #     image: "xd009642/tarpaulin:develop-nightly"
  #     options: --security-opt seccomp=unconfined
  #   steps:
  #     - uses: actions/checkout@v4
  #     - run: cargo install cargo-tarpaulin
  #     - run: cargo +nightly tarpaulin -o stdout -o html --timeout 120 --fail-under 95
  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: tarpaulin-report.zip
  #         path: tarpaulin-report.html
