FROM docker.io/rust:1-slim

# install cargo-tarpaulin system deps
RUN apt-get update && \
    apt-get install -y libssl-dev pkg-config && \
    apt-get clean

# install cargo-tarpaulin
RUN rustup default stable && \
    cargo install "cargo-tarpaulin@0.35.*"

# entry point
#
# note: you should specify the following parameters via the `with`
# directive in the step declaration:
#
# - engine
# - output
# - timeout
# - fail_under
ENTRYPOINT ["cargo", "tarpaulin"]
