name: CI

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_lint_test:
    name: "build, lint, test (${{ matrix.toolchain }})"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.cargo/advisory-db
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: rustup component add clippy
      - run: cargo build --verbose
      - run: cargo clippy
      - run: cargo test --verbose

  doc:
    name: "doc"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v6
      - run: cargo doc

  # lint all markdown
  lint_markdown:
    name: "lint markdown"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v5
      - run: npm config set update-notifier false
      - run: npx -y markdownlint-cli '**/*.md'

  # check code coverage
  # - fails if coverage drops below 98%
  # - generates "polycvss-coverage-YYYYMMDD.zip" artifact
  coverage:
    name: "coverage"
    runs-on: "ubuntu-latest"

    container:
      image: "xd009642/tarpaulin:develop-nightly"
      options: --security-opt seccomp=unconfined
    steps:
      - run: echo "DATESTAMP=$(date +%Y%m%d)" >> $GITHUB_ENV
      - uses: actions/checkout@v6
      - run: cargo +nightly tarpaulin -o html --timeout 120 --fail-under 98
      - run: mv tarpaulin-report.html polycvss-coverage-${{ env.DATESTAMP }}.html
      - uses: actions/upload-artifact@v6
        with:
          name: polycvss-coverage-${{ env.DATESTAMP }}.zip
          path: polycvss-coverage-${{ env.DATESTAMP }}.html

  # security audit
  # (note: mostly pointless since polycvss has no dependencies)
  audit:
    name: "audit"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.cargo/advisory-db
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo install cargo-audit
      - run: cargo audit
